### ISSUE TITLE
Pictures in CameraDisplay1M.zip need a new password but didnt find it

### ISSUE THREAD

**Issue by swzshazi** [mathski/LFM#3]
Hi there, I successfully download your data.zip and unzip it, but pictures in CameraDisplay1M.zip need a new password to unzip, please tell me please, thx a lot!

**Comment by Lee-meng-meng** [comment]
Did you solve this problem?

**Comment by Lee-meng-meng** [comment]
> Hi there, I successfully download your data.zip and unzip it, but pictures in CameraDisplay1M.zip need a new password to unzip, please tell me please, thx a lot!
Did you solve this problem?

**Comment by mathski** [comment]
Sorry about this. Rutgers has failed to provide the both of the correct passwords. Please email me (ericwengrowski@gmail.com) with your license file and I will send you the correct password.
